
train_classifier:
  dir: './results/resnet18'
  batch_size: 20
  num_epochs: 23
  num_grad_acc: 4

eval_classifier:
  batch_size: 20


loss_classifier:
  name: 'cross_entropy'
  
transform_classifier:
  name: 'policy_transform'
  num_preprocessor: 4
  params:
    policies: 'data/best_policy.data'
    per_image_norm: True
    size: 1024


